### ISSUE TITLE
Error in get_col_types: Unsupported object type: NULL Can't extract column types

### ISSUE THREAD

**Issue by abedkurdi** [infinity-a11y/PhyloTrace#13]
Hello there,

Thanks for the amazing tool! I was using it for Allelic Typing for multiple assembled genomes. However, at the end of the run, I was caught by the following error:

![Screenshot from 2024-06-14 13-19-51](https://github.com/infinity-a11y/PhyloTrace/assets/45813669/76f5993e-3d2e-452b-be20-2004772984a6)

and I tried to click on "visualization" to get the phylogenetic tree with no success. 

Any idea what is happening here?

Thanks in advance!

**Comment by infinity-a11y** [comment]
Thanks for sharing this issue.

The display of this error message is the result of a known error that occurs when none of the selected assemblies were successfully processed. Interestingly, the error count is also not displayed correctly in your case. The next patch 1.3.1 contains a fix for this error and will be released soon (probably next week). Please contact us via mail if you need help to resolve the difficulties with typing.

**Comment by abedkurdi** [comment]
Thank you so much for your prompt response! I will be waiting your next release then.

**Comment by infinity-a11y** [comment]
We resolved the bugged typing results with the release of [Version 1.4.0](https://github.com/infinity-a11y/PhyloTrace/releases/tag/v1.4.0). However this does not resolve the failing typing process occuring to you. Please reach out to us via mail if issues persist. 

To diagnose such problems we will implement logging in the coming version(s), which will help to resolve individual issues.
